# Writing prompts are from: https://biz.thyme-is-honey.com/blog/2021-10-25-90-journal-prompts/
# Please contact if you would like me to remove these prompts.

writing_prompts = {
    1: "Describe, in detail, what your life looks like 5 years from now. What do you do for fun? For work? Where do you live? Where do you drink your coffee in the morning?", 
    2: "If you had $100,000 magically appear in your bank account, how would you spend it?", 
    3: "If your body could speak to you, what would it say?", 
    4: "What things are currently keeping you awake at night or causing you stress?", 
    5: "If you could have telekinesis (moving things with your mind) or telepathy (ability to read minds) which would you choose and why?", 
    6: "Who are the five people you spend the most time with? How does each of them impact your life and behavior?", 
    7: 'Describe what home feels like? What places do you recognize as “home”?', 
    8: "If you could relive one year of your life, which which you choose and why?", 
    9: "Which people in your life have changed you for the better and how?", 
    10: "If I could go back and tell my 8-year-old self something, I would tell them ____.",
    11: "What is a skill you'd like to develop in the next five years?", 
    12: "When and where was the most memorable sunrise or sunset you have ever seen?", 
    13: "What are the best things in your life right now?", 
    14: "What is something that makes you unique?", 
    15: "Think of someone from your life you miss terribly. What would you say to them?", 
    16: "How do you deal with really stressful days? How could you navigate them better?", 
    17: "Describe, in detail, what your life looks like 10 years from now. What do you do for fun? For work? Where do you live? What do you do on the weekends?", 
    18: "What holiday traditions or annual rituals are the most important to you?", 
    19: "What foods or meals feel life-giving to you? How do they make you feel and what memories do you connect with them?", 
    20: "In what ways do you contribute to good in the world?",
    21: "Describe, in detail, what your life looks like 20 years from now. What do you do for fun? What does your family look like? Where do you live? Where do you drink your coffee in the morning?", 
    22: "If I could go back and tell my 18-year-old self something, I would tell them ____.", 
    23: "If you died tomorrow, what do you think your biggest impact on the world would have been?", 
    24: "When were you most outside of your comfort zone?", 
    25: "How will you know when you have reached ultimate success?", 
    26: "If you could travel anywhere, where would you go and why?", 
    27: "Tell the story of the most embarrassed you have ever been.", 
    28: "Name five people you consider mentors, and describe how they have impacted you personally or professionally.", 
    29: "Which films do you find yourself thinking about years after watching them?", 
    30: "What are the best things you learned from your grandparents?",
    31: "What new skills could you acquire in order to be happy or more successful?", 
    32: "What is a topic you could stand up and talk passionately about for five minutes? What would you say?", 
    33: "If you could change one thing about your personality or behavior, what would it be and why?", 
    34: "If you didn't have to worry about money or the opinions of others, what would you do with your life?", 
    35: "How would you want someone to describe you to others?", 
    36: "Write a quote that is meaningful to you. Explain why it impacts you.", 
    37: "When and where do you feel most comfortable and like yourself?", 
    38: "When was the last time that a scent reminded you of a childhood memory? What was it and where did it transport you?", 
    39: "What's the best outfit you've ever owned and why do you love it?", 
    40: "Describe the funniest thing you have ever seen happen in real life?",
    41: "If you had a million dollars and had to spend it in one week, how would you spend it?", 
    42: "Describe the best date you've ever been on.", 
    43: "Do you consider yourself conservative, moderate, or liberal in your political ideology? Has it changed over time? Do you think it will change in the future?", 
    44: "What are the most important things we can teach children?", 
    45: "What books do you find yourself still thinking about after reading them? ", 
    46: "What do you wish you would have learned in high school?", 
    47: "What are three things you wish you could have done differently in either high school or college?", 
    48: "What is your idea of a perfect Saturday? Describe it in detail starting with waking up.", 
    49: "When is the last time you laughed extremely hard? Where were you? Who were you with? What happened?", 
    50: "What have been your biggest accomplishments and achievements this year?",
    51: "How has technology made your life better or worse? How do you want that to change?", 
    52: "What is your most difficult relationship currently and what could you do to improve it?", 
    53: "Explain something you believed as a child that now makes you laugh.", 
    54: "What did you learn about marriage and relationships from your parents? Who else have you learned about relationships from?", 
    55: "Describe a trait you love about one of your parents. In what ways do you also have this trait?", 
    56: "Reflecting on the past year, what has been the best and worst moment?", 
    57: "If you could choose to see 10 years into the future or 100 years into the future which would you choose and why?", 
    58: "Describe your favorite photos of yourself. Where are you? What are you wearing? What were you doing before and after the photo was taken? How did you feel in that moment?", 
    59: "What does the sky look like today? How does it make you feel?", 
    60: "What is something that brings you profound joy? How could you get more of that in your life?",
    61: "If you could run any business and know it would succeed…what would it be?", 
    62: "What do you need MORE of in your life right now?", 
    63: "What's the best thing that happened to you in the last thirty days?", 
    64: "What was the most important lesson you've learned during the COVID pandemic? How will that impact your life moving forward?", 
    65: "Describe the things you wish more people knew about you and why.", 
    66: "In what ways do you want the next year to be different from the past year?", 
    67: "Describe something you do better than most people. What makes you uniquely good at it?", 
    68: "What is your daily routine like? How would you like to change it?", 
    69: "What areas of life exhaust you the most? What boundaries could you create to help with that?", 
    70: "Did you have a favorite book as a child? What was it and why did you love it so much?",
    71: "Name one song that means a lot to you. What does it remind you of? What does it mean to you? Why is it important to you?", 
    72: "Describe a big risk you've taken that you don't regret.", 
    73: "Identify the biggest distractions in your life and ways you can reduce or eliminate them.", 
    74: "If you were true to yourself, day in and day out, and if you fully accepted and loved yourself, what would change for you moving forward?", 
    75: "Name five things you want to do before you die and why did they make the list?", 
    76: "What are your favorite physical characteristics of yourself? What things make you unique from others?", 
    77: "Which things make you grateful to be alive, even on bad days?", 
    78: "Is there anything you've done this week that you wish you had done differently?", 
    79: "If you could have dinner with five people, living or dead, at your house, who would you invite and what would you cook for them?", 
    80: "What is something you have always wanted to do but have never done and why is it important to you?",
    81: "What is the last dream you had that you remembered after you woke up? What happened in it and how did it make you feel?", 
    82: "Do you have any talents that no one or very few people know about? Why don't more people know about it?", 
    83: "Which childhood memory are you the most grateful for? When do you find yourself thinking about that moment and why?", 
    84: "What physical activities or movements make you feel the happiest, joyful, and confident?", 
    85: "Which birthday was your best one and why? Who did you spend it with and what did you do?", 
    86: "What is the most memorable vacation you have ever been on and what made it so special?", 
    87: "What is the best or most memorable meal you've had so far in your life? Describe the dish. Where did you eat it? What time of day was it? Who were you with?", 
    88: "In what ways do you practice self-care? What do you need to do more of?", 
    89: "Identify three things you could give up that would give you more time, money, or peace.", 
    90: "Describe your favorite photo of yourself. Where are you? What are you wearing? What were you doing before and after the photo was taken? How did you feel at that moment?"
}
